# Generated by Django 5.1.5 on 2025-01-26 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='FoodsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Food Title')),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('images', models.FileField(default='foods.png', upload_to='foods/')),
                ('description', models.TextField()),
                ('rating', models.FloatField(default=0.0, verbose_name='Rating')),
                ('review', models.TextField(blank=True, verbose_name='Review')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='Foods.categorymodel')),
            ],
        ),
    ]
