# Generated by Django 5.1.5 on 2025-01-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0002_categorymodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsmodel',
            name='food_type',
            field=models.CharField(choices=[('Buff', 'Buff'), ('Chicken', 'Chicken'), ('Veg', 'Veg'), ('None', 'None')], default='None', max_length=50),
        ),
    ]
